export enum ToolsEnum {
    Bold = 'bold',
    Emoji = 'emoji',
    Blockquote = 'blockquote',
    Code = 'code',
    CodeBlock = 'codeBlock',
    Heading = 'heading',
    Highlight = 'highlight',
    Italic = 'italic',
    Link = 'link',
    TaskList = 'taskList',
    Subscript = 'subscript',
    Superscript = 'superscript',
    Table = 'table',
    TextAlign = 'textAlign',
    Underline = 'underline',
    Strike = 'strike',
    BulletList = 'bulletList',
    OrderedList = 'orderedList',
    TextStyle = 'textStyle',
    Undo = 'undo',
    Redo = 'redo',
}
